export const links = [
  {
    id: 1,
    text: 'Work',
    href: '/work',
    infiniteText: [
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work',
    ],
  },
  {
    id: 2,
    text: 'About',
    href: '/about',
    infiniteText: [
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About',
    ],
  },
  {
    id: 3,
    text: 'Community',
    href: '/community',
    infiniteText: [
      'Community ',
      'Community ',
      'Community ',
      'Community ',
      'Community ',
      'Community ',
      'Community ',
      'Community ',
      'Community ',
    ],
  },
  {
    id: 4,
    text: 'Jobs',
    href: '/jobs',
    infiniteText: [
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs',
      'Jobs',
      'Jobs',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs',
    ],
  },
  {
    id: 5,
    text: 'Contact',
    href: '/contact',
    infiniteText: [
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
    ],
  },
  {
    id: 6,
    text: 'Real Talk',
    href: '/',
    infiniteText: [
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
    ],
  },
];

export const homeWorkItems = [
  {
    id: 1,
    title: 'better battery co',
    src: '/img/better-battery-co.jpeg',
    type: 'img',
    text_left: 'Meet the World’s Most Positive Battery.',
    text_right: 'Creative Strategy Connections Production',
    href: '/',
  },
  {
    id: 2,
    title: 'Travel Edge',
    src: 'https://player.vimeo.com/video/651220811?autoplay=1&background=1&title=0&byline=0&portrait=0',
    type: 'video',
    text_left: 'Don’t Just Go On A Trip, Go On Your Trip.',
    text_right: 'Strategy Creative Connections Production',
    href: '/',
  },
  {
    id: 3,
    title: 'Jagermeister',
    src: '/img/jagermeister.jpg',
    type: 'img',
    text_left: 'Taste what Flula means.',
    text_right: 'Creative Production Connections Strategy',
    href: '/',
  },
];

export const homeBlogScrollItems = [
  {
    id: 1,
    mainTitle: 'for the love of live',
    subTitleText: 'do good',
    subTitleDate: '04-04-2022',
    img: '/img/for-the-love-of-live.jpg',
    icon: '/icon/for-the-love-of-live-shape.svg',
    href: '/',
  },
  {
    id: 2,
    mainTitle: 'little local ad',
    subTitleText: 'do good',
    subTitleDate: '18-07-2021',
    img: '/img/little-local-ad.jpg',
    icon: '/icon/little-local-ad-shape.svg',
    href: '/',
  },
  {
    id: 3,
    mainTitle: 'homepage for chance',
    subTitleText: 'do good',
    subTitleDate: '06-12-2021',
    img: '/img/home-page-for-chance.jpg',
    icon: '/icon/home-page-for-change-shape.svg',
    href: '/',
  },
  {
    id: 4,
    mainTitle: 'snowbirds',
    subTitleText: 'social',
    subTitleDate: '22-03-2022',
    img: '/img/snowbirds.jpg',
    icon: '/icon/snowbirds-shape.svg',
    href: '/',
  },
  {
    id: 5,
    mainTitle: 'monthly debate',
    subTitleText: 'social',
    subTitleDate: '01-04-2021',
    img: '/img/monthly-debate.jpg',
    icon: '/icon/monthly-debate-shape.svg',
    href: '/',
  },
];

export const footerDynamicWords = [
  'salam',
  'ola',
  'yasou',
  'hello',
  'hi',
  'howhy',
  'marhaba',
  'bonjour',
  'hey',
  "g'day",
  'holla',
  'howdy',
  'ahoj',
  'namaste',
  'konnichiwa',
];

export const workListItem = [
  {
    id: 1,
    mainTitle: 'DIRECTORS GUILD',
    subTitle: 'WIDER LENS.',
    text: 'Strategy Creative Connections Editorial Production',
    img: '/img/directors-guild.jpg',
    href: '/',
  },
  {
    id: 2,
    mainTitle: 'FRESHCO',
    subTitle: 'WE LET OUR PRICES DO THE TALKING.',
    text: 'Creative Production Strategy',
    img: '/img/freshco.jpg',
    href: '/',
  },
  {
    id: 3,
    mainTitle: 'BETTER BATTERY CO',
    subTitle: 'MEET THE WORLD’S MOST POSITIVE BATTERY.',
    text: 'Creative Strategy Connections Production',
    img: '/img/better-battery-co.jpeg',
    href: '/',
  },
  {
    id: 4,
    mainTitle: 'REDBARN',
    subTitle: 'WHERE DOG DREAMS COME TRUE.',
    text: 'Strategy Creative Design',
    img: '/img/redbarn.jpg',
    href: '/',
  },
  {
    id: 5,
    mainTitle: 'TRAVEL EDGE',
    subTitle: 'DON’T JUST GO ON A TRIP, GO ON YOUR TRIP.',
    text: 'Strategy Creative Connections Production',
    img: '/img/travel-edge.jpeg',
    href: '/',
  },
  {
    id: 6,
    mainTitle: 'MOROCCAN OIL',
    subTitle: 'BODY CARE THAT TAKES YOU THERE.',
    text: 'Creative Production Connections',
    img: '/img/maroccan-oil.jpg',
    href: '/',
  },
  {
    id: 7,
    mainTitle: 'THE BURGER’S PRIEST',
    subTitle: 'HAVE FAITH.',
    text: 'Strategy Creative Design',
    img: '/img/the-burgers-priest.jpg',
    href: '/',
  },
  {
    id: 8,
    mainTitle: 'GRAND MARNIER',
    subTitle: 'THE GRAND GOOD RIDDANCE.',
    text: 'Strategy Creative Connections Production',
    img: '/img/grand-marnier.jpg',
    href: '/',
  },
  {
    id: 9,
    mainTitle: 'ZALES',
    subTitle: 'MARILYN MONROE.',
    text: 'Creative Connections Production Strategy',
    img: '/img/zales.jpg',
    href: '/',
  },
  {
    id: 10,
    mainTitle: 'MAILCHIMP',
    subTitle: 'GROWING A COMMUNITY OF PARTNERS.',
    text: 'Strategy Creative Editorial Connections Production',
    img: '/img/mailchimp.jpg',
    href: '/',
  },
  {
    id: 11,
    mainTitle: 'VERA WANG',
    subTitle: 'FUREVER LOVE.',
    text: 'Connections Creative Production Strategy',
    img: '/img/vera-wang.png',
    href: '/',
  },
  {
    id: 12,
    mainTitle: 'JAGERMEISTER',
    subTitle: 'TASTE WHAT FLULA MEANS.',
    text: ' Creative Production Connections Strategy',
    img: '/img/jagermeister.jpg',
    href: '/',
  },
  {
    id: 13,
    mainTitle: 'S BY SERENA',
    subTitle: 'IT’S YOUR TURN TO PLAY.',
    text: 'Connections Creative Production Strategy',
    img: '/img/s-by-serena.jpg',
    href: '/',
  },
  {
    id: 14,
    mainTitle: 'SICKKIDS HOSPITAL',
    subTitle: 'HEART MONTH.',
    text: 'Connections Creative Production',
    img: '/img/sickkids-hospital.jpg',
    href: '/',
  },
  {
    id: 15,
    mainTitle: 'DOJA',
    subTitle: 'PARDON PRODUCTS.',
    text: 'Creative Production',
    img: '/img/doja.jpeg',
    href: '/',
  },
];

export const communityArticles = [
  {
    id: 1,
    category: 'Do good',
    img: '/img/for-the-love-of-live.jpg',
    mask: '/icon/for-the-love-of-live-shape-2.svg',
    title: 'For the love of live',
    date: '04-05-2022',
    size: 'large',
  },
  {
    id: 2,
    category: 'Social',
    img: '/img/snowbirds.jpg',
    mask: '/icon/snowbirds-shape-2.svg',
    title: 'Snowbirds',
    date: '22-03-2022',
    size: 'large',
  },
  {
    id: 3,
    category: 'Do good',
    img: '/img/home-page-for-chance.jpg',
    mask: '/icon/home-page-for-change-shape-2.svg',
    title: 'Homepage for Change',
    date: '06-12-2021',
    size: 'large',
  },
  {
    id: 4,
    category: 'Do good',
    img: '/img/little-local-ad.jpg',
    mask: '/icon/little-local-ad-shape-2.svg',
    title: 'Little Local Ad',
    date: '18-07-2021',
    size: 'small',
  },
  {
    id: 5,
    category: 'Social',
    img: '/img/monthly-debate.jpg',
    mask: '/icon/monthly-debate-shape-2.svg',
    title: 'The Monthly Debate',
    date: '01-04-2021',
    size: 'small',
  },
  {
    id: 6,
    category: '',
    img: '/img/monthly-debate.jpg',
    mask: '/icon/monthly-debate-shape-2.svg',
    title: '',
    date: '',
    size: '',
  },
];
