export const links = [
  {
    id: 1,
    text: 'Work',
    href: '/',
    infiniteText: [
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work',
    ],
  },
  {
    id: 2,
    text: 'About',
    href: '/',
    infiniteText: [
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About',
    ],
  },
  {
    id: 3,
    text: 'Community',
    href: '/',
    infiniteText: [
      'Community ',
      'Community ',
      'Community ',
      'Community ',
      'Community ',
      'Community ',
      'Community ',
      'Community ',
      'Community ',
      'Community ',
    ],
  },
  {
    id: 4,
    text: 'Jobs',
    href: '/',
    infiniteText: [
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs',
      'Jobs',
      'Jobs',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs',
      'Jobs',
      'Jobs',
    ],
  },
  {
    id: 5,
    text: 'Contact',
    href: '/',
    infiniteText: [
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
    ],
  },
  {
    id: 6,
    text: 'Real Talk',
    href: '/',
    infiniteText: [
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
    ],
  },
];

export const homeWorkItems = [
  {
    id: 1,
    title: 'better battery co',
    src: '/img/hero-better-battery-co.jpeg',
    type: 'img',
    text_left: 'Meet the World’s Most Positive Battery.',
    text_right: 'Creative Strategy Connections Production',
    href: '/',
  },
  {
    id: 2,
    title: 'Travel Edge',
    src: 'https://player.vimeo.com/video/651220811?autoplay=1&background=1&title=0&byline=0&portrait=0',
    type: 'video',
    text_left: 'Don’t Just Go On A Trip, Go On Your Trip.',
    text_right: 'Strategy Creative Connections Production',
    href: '/',
  },
  {
    id: 3,
    title: 'Jagermeister',
    src: '/img/hero-jägermeister.jpeg',
    type: 'img',
    text_left: 'Taste what Flula means.',
    text_right: 'Creative Production Connections Strategy',
    href: '/',
  },
];

export const homeBlogScrollItems = [
  {
    id: 1,
    mainTitle: 'for the love of live',
    subTitleText: 'do good',
    subTitleDate: '04-04-2022',
    img: '/img/for-the-love-of-live.jpg',
    icon: '/icon/for-the-love-of-live-shape.svg',
    href: '/',
  },
  {
    id: 2,
    mainTitle: 'little local ad',
    subTitleText: 'do good',
    subTitleDate: '18-07-2021',
    img: '/img/little-local-ad.jpg',
    icon: '/icon/little-local-ad-shape.svg',
    href: '/',
  },
  {
    id: 3,
    mainTitle: 'homepage for chance',
    subTitleText: 'do good',
    subTitleDate: '06-12-2021',
    img: '/img/home-page-for-chance.jpg',
    icon: '/icon/home-page-for-change-shape.svg',
    href: '/',
  },
  {
    id: 4,
    mainTitle: 'snowbirds',
    subTitleText: 'social',
    subTitleDate: '22-03-2022',
    img: '/img/snowbirds.jpg',
    icon: '/icon/snowbirds-shape.svg',
    href: '/',
  },
  {
    id: 5,
    mainTitle: 'monthly debate',
    subTitleText: 'social',
    subTitleDate: '01-04-2021',
    img: '/img/monthly-debate.jpg',
    icon: '/icon/monthly-debate-shape.svg',
    href: '/',
  },
];

export const footerDynamicWords = [
  'salam',
  'ola',
  'yasou',
  'hello',
  'hi',
  'howhy',
  'marhaba',
  "what's up",
  'bonjour',
  'hey',
  'guten tag',
  "g'day",
  'dobryj den',
  'holla',
  'howdy',
  "what' up",
  'ahoj',
  'namaste',
  'konnichiwa',
];
