export const links = [
  {
    id: 1,
    text: 'Work',
    href: '/work',
    infiniteText: [
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work ',
      'Work',
    ],
  },
  {
    id: 2,
    text: 'About',
    href: '/about',
    infiniteText: [
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About ',
      'About',
    ],
  },
  {
    id: 3,
    text: 'Community',
    href: '/community',
    infiniteText: [
      'Community ',
      'Community ',
      'Community ',
      'Community ',
      'Community ',
      'Community ',
      'Community ',
      'Community ',
      'Community ',
    ],
  },
  {
    id: 4,
    text: 'Jobs',
    href: '/jobs',
    infiniteText: [
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs',
      'Jobs',
      'Jobs',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs ',
      'Jobs',
    ],
  },
  {
    id: 5,
    text: 'Contact',
    href: '/contact',
    infiniteText: [
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
      'Contact ',
    ],
  },
  {
    id: 6,
    text: 'Real Talk',
    href: 'https://realtalkinsights.com/',
    infiniteText: [
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
      'Real Talk ',
    ],
  },
];

export const homeWorkItems = [
  {
    id: 1,
    title: 'better battery co',
    src: '/img/better-battery-co.jpeg',
    type: 'img',
    text_left: 'Meet the World’s Most Positive Battery.',
    text_right: 'Creative Strategy Connections Production',
  },
  {
    id: 2,
    title: 'Travel Edge',
    src: 'https://player.vimeo.com/video/651220811?autoplay=1&background=1&title=0&byline=0&portrait=0',
    type: 'video',
    text_left: 'Don’t Just Go On A Trip, Go On Your Trip.',
    text_right: 'Strategy Creative Connections Production',
  },
  {
    id: 3,
    title: 'Jagermeister',
    src: '/img/jagermeister.jpg',
    type: 'img',
    text_left: 'Taste what Flula means.',
    text_right: 'Creative Production Connections Strategy',
  },
];

export const homeBlogScrollItems = [
  {
    id: 1,
    mainTitle: 'for the love of live',
    subTitleText: 'do good',
    subTitleDate: '04-04-2022',
    img: '/img/for-the-love-of-live.jpg',
    icon: '/icon/shape-1.svg',
  },
  {
    id: 2,
    mainTitle: 'little local ad',
    subTitleText: 'do good',
    subTitleDate: '18-07-2021',
    img: '/img/little-local-ad.jpg',
    icon: '/icon/shape-5.svg',
  },
  {
    id: 3,
    mainTitle: 'homepage for chance',
    subTitleText: 'do good',
    subTitleDate: '06-12-2021',
    img: '/img/home-page-for-chance.jpg',
    icon: '/icon/shape-3.svg',
  },
  {
    id: 4,
    mainTitle: 'snowbirds',
    subTitleText: 'social',
    subTitleDate: '22-03-2022',
    img: '/img/snowbirds.jpg',
    icon: '/icon/shape-8.svg',
  },
  {
    id: 5,
    mainTitle: 'monthly debate',
    subTitleText: 'social',
    subTitleDate: '01-04-2021',
    img: '/img/monthly-debate.jpg',
    icon: '/icon/shape-7.svg',
  },
];

export const footerDynamicWords = [
  'salam',
  'ola',
  'yasou',
  'hello',
  'hi',
  'howhy',
  'marhaba',
  'bonjour',
  'hey',
  "g'day",
  'holla',
  'howdy',
  'ahoj',
  'namaste',
  'konnichiwa',
];

export const workListItem = [
  {
    id: 1,
    mainTitle: 'DIRECTORS GUILD',
    subTitle: 'WIDER LENS.',
    text: 'Strategy Creative Connections Editorial Production',
    img: '/img/directors-guild.jpg',
  },
  {
    id: 2,
    mainTitle: 'FRESHCO',
    subTitle: 'WE LET OUR PRICES DO THE TALKING.',
    text: 'Creative Production Strategy',
    img: '/img/freshco.jpg',
  },
  {
    id: 3,
    mainTitle: 'BETTER BATTERY CO',
    subTitle: 'MEET THE WORLD’S MOST POSITIVE BATTERY.',
    text: 'Creative Strategy Connections Production',
    img: '/img/better-battery-co.jpeg',
  },
  {
    id: 4,
    mainTitle: 'REDBARN',
    subTitle: 'WHERE DOG DREAMS COME TRUE.',
    text: 'Strategy Creative Design',
    img: '/img/redbarn.jpg',
  },
  {
    id: 5,
    mainTitle: 'TRAVEL EDGE',
    subTitle: 'DON’T JUST GO ON A TRIP, GO ON YOUR TRIP.',
    text: 'Strategy Creative Connections Production',
    img: '/img/travel-edge.jpeg',
  },
  {
    id: 6,
    mainTitle: 'MOROCCAN OIL',
    subTitle: 'BODY CARE THAT TAKES YOU THERE.',
    text: 'Creative Production Connections',
    img: '/img/maroccan-oil.jpg',
  },
  {
    id: 7,
    mainTitle: 'THE BURGER’S PRIEST',
    subTitle: 'HAVE FAITH.',
    text: 'Strategy Creative Design',
    img: '/img/the-burgers-priest.jpg',
  },
  {
    id: 8,
    mainTitle: 'GRAND MARNIER',
    subTitle: 'THE GRAND GOOD RIDDANCE.',
    text: 'Strategy Creative Connections Production',
    img: '/img/grand-marnier.jpg',
  },
  {
    id: 9,
    mainTitle: 'ZALES',
    subTitle: 'MARILYN MONROE.',
    text: 'Creative Connections Production Strategy',
    img: '/img/zales.jpg',
  },
  {
    id: 10,
    mainTitle: 'MAILCHIMP',
    subTitle: 'GROWING A COMMUNITY OF PARTNERS.',
    text: 'Strategy Creative Editorial Connections Production',
    img: '/img/mailchimp.jpg',
  },
  {
    id: 11,
    mainTitle: 'VERA WANG',
    subTitle: 'FUREVER LOVE.',
    text: 'Connections Creative Production Strategy',
    img: '/img/vera-wang.png',
  },
  {
    id: 12,
    mainTitle: 'JAGERMEISTER',
    subTitle: 'TASTE WHAT FLULA MEANS.',
    text: ' Creative Production Connections Strategy',
    img: '/img/jagermeister.jpg',
  },
  {
    id: 13,
    mainTitle: 'S BY SERENA',
    subTitle: 'IT’S YOUR TURN TO PLAY.',
    text: 'Connections Creative Production Strategy',
    img: '/img/s-by-serena.jpg',
  },
  {
    id: 14,
    mainTitle: 'SICKKIDS HOSPITAL',
    subTitle: 'HEART MONTH.',
    text: 'Connections Creative Production',
    img: '/img/sickkids-hospital.jpg',
  },
  {
    id: 15,
    mainTitle: 'DOJA',
    subTitle: 'PARDON PRODUCTS.',
    text: 'Creative Production',
    img: '/img/doja.jpeg',
  },
];

export const communityArticles = [
  {
    id: 1,
    category: 'Do good',
    img: '/img/for-the-love-of-live.jpg',
    mask: '/icon/shape-2.svg',
    title: 'For the love of live',
    date: '04-05-2022',
    size: 'large',
  },
  {
    id: 2,
    category: 'Social',
    img: '/img/snowbirds.jpg',
    mask: '/icon/shape-9.svg',
    title: 'Snowbirds',
    date: '22-03-2022',
    size: 'large',
  },
  {
    id: 3,
    category: 'Do good',
    img: '/img/home-page-for-chance.jpg',
    mask: '/icon/shape-4.svg',
    title: 'Homepage for Change',
    date: '06-12-2021',
    size: 'large',
  },
  {
    id: 4,
    category: 'Do good',
    img: '/img/little-local-ad.jpg',
    mask: '/icon/shape-3.svg',
    title: 'Little Local Ad',
    date: '18-07-2021',
    size: 'small',
  },
  {
    id: 5,
    category: 'Social',
    img: '/img/monthly-debate.jpg',
    mask: '/icon/shape-7.svg',
    title: 'The Monthly Debate',
    date: '01-04-2021',
    size: 'small',
  },
  {
    id: 6,
    category: '',
    img: '/img/monthly-debate.jpg',
    mask: '/icon/shape-3.svg',
    title: '',
    date: '',
    size: '',
  },
];

export const aboutTeam = [
  {
    id: 1,
    firstName: 'Leanne',
    lastName: 'Goldstein',
    role: 'Partner, President',
    img: '/img/team-1.jpg',
    shape: '/icon/shape-3.svg',
  },
  {
    id: 2,
    firstName: 'Ryan',
    lastName: 'Spelliscy',
    role: 'Co-Founder, CEO, Chief Creative Officer',
    img: '/img/team-2.jpg',
    shape: '/icon/shape-6.svg',
  },
  {
    id: 3,
    firstName: 'Laurent',
    lastName: 'Abesdris',
    role: 'Partner Creative Director',
    img: '/img/team-3.jpg',
    shape: '/icon/shape-1.svg',
  },
  {
    id: 4,
    firstName: 'Susan',
    lastName: 'Holden',
    role: 'Chief Financial Officer',
    img: '/img/team-4.jpg',
    shape: '/icon/shape-5.svg',
  },
  {
    id: 5,
    firstName: 'Kaiti',
    lastName: 'Snell',
    role: 'Partner, Co-Head of Strategy',
    img: '/img/team-5.jpg',
    shape: '/icon/shape-8.svg',
  },
  {
    id: 6,
    firstName: 'Andrew',
    lastName: 'Schulze',
    role: 'Head of Production',
    img: '/img/team-6.jpg',
    shape: '/icon/shape-7.svg',
  },
  {
    id: 7,
    firstName: 'Marc',
    lastName: 'Pardy',
    role: 'Partner, Co-Head of Strategy',
    img: '/img/team-7.jpg',
    shape: '/icon/shape-5.svg',
  },
];

export const aboutWhat = [
  {
    id: 1,
    title: 'Design',
    text: 'From logo refreshes to complete visual systems, our design team ensures your brand is saying the right things visually.',
  },
  {
    id: 2,
    title: 'Digital',
    text: 'Digital advertising. Visual, UX design and optimization. Complete site development to Shopify storefronts.    ',
  },
  {
    id: 3,
    title: 'Real Talk',
    text: 'Fast company calls it the focus group of the future. It’s more than research. It’s a way to have ongoing conversations with the audiences you need to love to win. ',
  },
  {
    id: 4,
    title: 'Studioland',
    text: 'High quality production facility out of Los Angeles. Post production capabilities, editing suites. ',
  },
  {
    id: 5,
    title: 'Social',
    text: 'Social solutions, including day-to-day community management. Powered by an editorial team made up of designers, former journalists, creatives, and mid-to-long-form writers.',
  },
];

export const aboutClients = [
  {
    id: 1,
    img: '/icon/client-mailchimp.png',
  },
  {
    id: 2,
    img: '/icon/client-GCE.png',
  },
  {
    id: 3,
    img: '/icon/client-smirnoff.png',
  },
  {
    id: 4,
    img: '/icon/client-jager.png',
  },
  {
    id: 5,
    img: '/icon/client-moroccanoil.png',
  },
  {
    id: 6,
    img: '/icon/client-redbarn.png',
  },
  {
    id: 7,
    img: '/icon/client-CCS.png',
  },
  {
    id: 8,
    img: '/icon/client-traveledge.png',
  },
  {
    id: 9,
    img: '/icon/client-podium.png',
  },
  {
    id: 10,
    img: '/icon/client-DGC.png',
  },
  {
    id: 11,
    img: '/icon/client-theburgerspriest.png',
  },
  {
    id: 12,
    img: '/icon/client-BBCO.png',
  },
  {
    id: 13,
    img: '/icon/client-goodleaf.png',
  },
  {
    id: 14,
    img: '/icon/client-freshco.png',
  },
  {
    id: 15,
    img: '/icon/client-culina.png',
  },
  {
    id: 16,
    img: '/icon/client-lawtons.png',
  },
];
